from . import haydovchi_reys_asosiy
from . import hardovchi_reys_andijon
from . import haydovchi_reys_namangan
from . import haydovchi_reys_fargona
from . import haydovchi_reys_buxoro
from . import haydovchi_reys_toshkent
from . import haydovchi_reys_sirdaryo
from . import haydovchi_reys_surxondaryo
from . import haydovchi_reys_qashqadaryo
from . import haydovchi_reys_xorazm
from . import haydovchi_reys_jizzax
from . import haydovchi_reys_samarqand
from . import haydochi_reys_navoiy