from . import sayohat_asosiy
from . import sayohat_andijon
from . import sayohat_namangan
from . import sayohat_fargona
from . import sayohat_buxoro
from . import sayohat_toshkent
from . import sayohat_sirdaryo
from . import sayohat_surxondaryo
from . import sayohat_qashqadaryo
from . import sayohat_xorazm
from . import sayohat_navoiy
from . import sayohat_jizzax
from . import sayohat_samarqand