from . import haydovchi_pochta_asosiy
from . import reys_pochta_andijon
from . import reys_pochta_fargona
from . import reys_pochta_buxoro
from . import reys_pochta_toshkent
from . import reys_pochta_sirdaryo
from . import reys_pochta_surxondaryo
from . import reys_pochta_qashqadaryo
from . import reys_pochta_xorazm
from . import reys_pochta_navoiy
from . import reys_pochta_jizzax
from . import reys_pochta_samarqand