from . import asosiy
from . import hay_sayohat_andijon
from . import hay_sayohat_namangan
from . import hay_sayohat_fargona
from . import hay_sayohat_buxoro
from . import hay_sayohat_toshkent
from . import hay_sayohat_sirdaryo
from . import hay_sayohat_surxondaryo
from . import hay_sayohat_qashqadaryo
from . import hay_sayohat_xorazm
from . import hay_sayohat_navoiy
from . import hay_sayohat_jizzax
from . import hay_sayohat_samarqand