from . import andijon_yuk
from . import namangan_yuk
from . import fargona_yuk
from . import buxoro_yuk
from . import toshkent_yuk
from . import sirdaryo_yuk
from . import surxondaryo_yuk
from . import qashqadaryo_yuk
from . import xorazm_yuk
from . import navoiy_yuk
from . import jizzax_yuk
from . import samarqand_yuk
from . import yuk_yuborish_asosiy