from . import yuk_reys_asosiy
from . import yuk_reys_andijon
from . import yuk_reys_namangan
from . import yuk_reys_fargona
from . import yuk_reys_buxoro
from . import yuy_reys_toshkent
from . import yuk_reys_sirdaryo
from . import yuk_reys_surxondaryo
from . import yuk_reys_qashqadaryo
from . import yuk_reys_xorazm
from . import yuk_reys_navoiy
from . import yuk_reys_jizzax
from . import yuk_reys_samarqand