from aiogram.dispatcher.filters.state import StatesGroup, State



class Hay_say_andijon(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()

class Hay_say_namangan(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()


class Hay_say_fargona(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()

class Hay_say_buxoro(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()

class Hay_say_toshkent(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()

class Hay_say_sirdaryo(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()
class Hay_say_surxon(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()
class Hay_say_qashqadaryo(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()
class Hay_say_xorazm(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()



class Hay_say_navoiy(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()


class Hay_say_jizzax(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()



class Hay_say_samarqand(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()