from aiogram.dispatcher.filters.state import StatesGroup, State



class Reys_pochta_andijon(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()

class Reys_pochta_namangan(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()


class Reys_pochta_fargona(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()

class Reys_pochta_buxoro(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()

class Reys_pochta_toshkent(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()

class Reys_pochta_sirdaryo(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()
class Reys_pochta_surxon(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()
class Reys_pochta_qashqadaryo(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()
class Reys_pochta_xorazm(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()



class Reys_pochta_navoiy(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()


class Reys_pochta_jizzax(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()



class Reys_pochta_samarqand(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()