from aiogram.dispatcher.filters.state import StatesGroup, State



class Reys_andijon(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()

class Reys_namangan(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()


class Reys_fargona(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()

class Reys_buxoro(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()

class Reys_toshkent(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()

class Reys_sirdaryo(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()
class Reys_surxon(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()
class Reys_qashqadaryo(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()
class Reys_xorazm(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()



class Reys_navoiy(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()


class Reys_jizzax(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()



class Reys_samarqand(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    end = State()