from aiogram.dispatcher.filters.state import StatesGroup, State


class Sayohat_andijon(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()


class Sayohat_fargona(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()


class Sayohat_namangan(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()


class Sayohat_buxoro(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()

class Sayohat_jizzax(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()



class Sayohat_navoiy(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()

class Sayohat_qash(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()

class Sayohat_sam(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()


class Sayohat_sir(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()


class Sayohat_surx(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()



class Sayohat_tosh(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()


class Sayohat_xor(StatesGroup):
    tuman=State()
    sayohat_manzillari=State()
    sana=State()
    soat=State()
    turi =State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kun = State()
    necha_kishi = State()
    qancha_narx = State()
    end = State()