from aiogram.dispatcher.filters.state import State,StatesGroup

class Yolovchi_andijon(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()

class Yolovchi_fargon(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()



class Yolovchi_toshkent(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()



class Yolovchi_namangan(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()



class Yolovchi_buxoro(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()

class Yolovchi_sirdaryo(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()


class Yolovchi_surxondaryo(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()

class Yolovchi_qashqadaryo(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()


class Yolovchi_xorazm(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()

class Yolovchi_navoiy(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()


class Yolovchi_jizzax(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()

class Yolovchi_samar(StatesGroup):
    tuman = State()
    viloyatga = State()
    tumaniga = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    oldi_kerakmi = State()
    qanday_moshina = State()
    end = State()
