from aiogram.dispatcher.filters.state import StatesGroup, State



class Yuk_reys_andijon(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()


class Yuk_reys_namangan(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()


class Yuk_reys_fargona(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()


class Yuk_reys_buxoro(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()


class Yuk_reys_sirdaryo(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()
class Yuk_reys_surxondaryo(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()
class Yuk_reys_toshkent(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()


class Yuk_reys_qashqadaryo(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()



class Yuk_reys_samarqand(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()

class Yuk_reys_jizzax(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()
class Yuk_reys_navoiy(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()


class Yuk_reys_xorazm(StatesGroup):
    tuman=State()
    viloyatga=State()
    tumaniga=State()
    kuni = State()
    soat=State()
    phone=State()
    locatsiya=State()
    tasdiqlash=State()
    xa_yoq=State()
    necha_kishi = State()
    qanday_moshina = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    jami_odam =State()
    oldi_orin = State()
    odam = State()
    end = State()