from aiogram.dispatcher.filters.state import State,StatesGroup

class Yuk_andijon(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()


class Yuk_namangan(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()

class Yuk_fargona(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()
class Yuk_buxoro(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()


class Yuk_toshkent(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()



class Yuk_sirdaryo(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()


class Yuk_surxondaryo(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()



class Yuk_qashqadaryo(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()




class Yuk_xorazm(StatesGroup):
    asosiy = State()
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()


class Yuk_navoiy(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()


class Yuk_jizzax(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()


class Yuk_samarqand(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()



class Yuk_toshkent_shahar(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()



class Yuk_qoraqalpoq(StatesGroup):
    qolda_odam_soni = State()
    qolda_yozish = State()
    oyini_kiritsh = State()
    kunini_kiritsh = State()
    tuman = State()
    pul_qol = State()
    qolda_yoz = State()
    viloyatga = State()
    tumaniga = State()
    kuni = State()
    oyi = State()
    aniq_kuni = State()
    soat = State()
    phone = State()
    locatsiya = State()
    tasdiqlash = State()
    xa_yoq = State()
    necha_kishi = State()
    qanday_moshina = State()
    jami_odam = State()
    oldi_orin = State()
    odam = State()
    odam_vil = State()
    odam_tuman = State()
    tuman_yol = State()
    pochta_olasizmi = State()
    yuk_olasizmi = State()
    end = State()
    oldi_kerakmi = State()