from . import namangan_edit
from . import qoraqalpoq_edit
from . import toshkent_shahar_edit
from . import qashqadaryo_edit
from . import samarqand_edit
from . import sirdaryo_edit
from . import surxondaryo_edit
from . import toshjent_edit
from . import sozlamalar