from . import pochta_andijon
from . import pochta_namangan
from . import pochta_fargona
from . import pochta_buxoro
from . import pochta_tohkent
from . import pochta_sirdaryo
from . import pochta_surxondaryo
from . import pochta_qashqadaryo
from . import pochta_navoiy
from . import pochta_jizzax
from . import pochta_samarqand
from . import pochta_xorazm
from . import pochta_asosiy