from . import andijon
from . import fargona
from . import namangan
from . import toshkent
from . import buxoro
from . import navoiy
from . import jizzax
from . import sirdaryo
from . import surxondaryo
from . import qashqadaryo
from . import xorazm
from . import samarqand